version: 2

sources:
  - name: bronze
    # This dynamically switches the schema based on the environment
    schema: "{{ var('DBT_render_schema', 'main') }}" 

    tables:
      - name: raw_octopus_consumption
      - name: raw_octopus_tariffs
      - name: raw_octopus_agreements