version: 2

sources:
  - name: bronze
    schema: "{{ 'main' if target.type == 'duckdb' else 'octopus_energy_data' }}"
    tables:
      - name: raw_octopus_consumption
      - name: raw_octopus_tariffs
      - name: raw_octopus_agreements
